### PR TITLE
hook up metrics and refactor

### PR DESCRIPTION
**Pull request by javasoze**

### CODE REVIEW

**Comment by joway** [comment]
we now may start more than 50 java process ... because we need to write log files at same time. so if you start a http port, we may not can start multi process

**Comment by joway** [comment]
i see your code, you using slf4j and you can not write multi log files at the same time, right?

**Comment by javasoze** [comment]
@joway in config.yml, if we set the ports to 0, then it will pick a random port and it I verified that it will work.
As for logs, I thought you are using different log names in the script?

**Comment by joway** [comment]
yes, we start 50 java process and use different logname.

**Pull request merged**
